from django.urls import path

from ..views.salons import (
    SalonEmployeeDetailView,
    SalonListView,
    SalonDetailView,
    SalonServiceListView,
    SalonServiceDetailView,
    SalonProductListView,
    SalonProductDetailView,
    SalonEmployeeListView,
    SalonChairListView,
    SalonChairDetailView,
    SalonChairBookingListView,
    SalonChairBookingDetailView,
    SalonBookingListView,
    SalonBookingDetailView,
)

urlpatterns = [
    path(
        "/<uuid:salon_uid>/chairs/<uuid:chair_uid>/bookings/<uuid:booking_uid>",
        SalonChairBookingDetailView.as_view(),
        name="salon.chair-booking-detail",
    ),
    path(
        "/<uuid:salon_uid>/chairs/<uuid:chair_uid>/bookings",
        SalonChairBookingListView.as_view(),
        name="salon.chair-booking-list",
    ),
    path(
        "/<uuid:salon_uid>/chairs/<uuid:chair_uid>",
        SalonChairDetailView.as_view(),
        name="salon.chair-detail",
    ),
    path(
        "/<uuid:salon_uid>/chairs",
        SalonChairListView.as_view(),
        name="salon.chair-list",
    ),
    path(
        "/<uuid:salon_uid>/bookings/<uuid:booking_uid>",
        SalonBookingDetailView.as_view(),
        name="salon.booking-detail",
    ),
    path(
        "/<uuid:salon_uid>/bookings",
        SalonBookingListView.as_view(),
        name="salon.booking-list",
    ),
    path(
        "/<uuid:salon_uid>/employees/<uuid:employee_uid>",
        SalonEmployeeDetailView.as_view(),
        name="salon.employee-detail",
    ),
    path(
        "/<uuid:salon_uid>/employees",
        SalonEmployeeListView.as_view(),
        name="salon.employee-list",
    ),
    path(
        "/<uuid:salon_uid>/products/<uuid:product_uid>",
        SalonProductDetailView.as_view(),
        name="salon.product-detail",
    ),
    path(
        "/<uuid:salon_uid>/products",
        SalonProductListView.as_view(),
        name="salon.product-list",
    ),
    path(
        "/<uuid:salon_uid>/services/<uuid:service_uid>",
        SalonServiceDetailView.as_view(),
        name="salon.service-detail",
    ),
    path(
        "/<uuid:salon_uid>/services",
        SalonServiceListView.as_view(),
        name="salon.service-list",
    ),
    path(
        "/<uuid:salon_uid>",
        SalonDetailView.as_view(),
        name="salon.detail",
    ),
    path("", SalonListView.as_view(), name="salon.list"),
]
