from django.urls import path

from ..views.salons import (
    SalonListView,
    SalonDetailView,
    SalonDashboardApiView,
    SalonServiceListView,
    SalonServiceDetailView,
    SalonProductListView,
    SalonProductDetailView,
    SalonEmployeeListView,
    SalonEmployeeDetailView,
    SalonChairListView,
    SalonChairDetailView,
    SalonChairBookingListView,
    SalonChairBookingDetailView,
    SalonbookingListView,
    SalonBookingDetailView,
    SalonBookingCalendarListView,
    SalonBookingCalendarDetailView,
    SalonLookBookListView,
    SalonLookBookDetailView,
    SalonBookingReceiptDownloadAPIView,
    TopServiceCategoryRevenueView,
    TopProductCategoryRevenueView,
    TopServicesRevenueView,
    TopProductsRevenueView
)

urlpatterns = [
    path("/<uuid:salon_uid>/analytics/product-revenue", TopProductsRevenueView, name="product-revenue"),
    path("/<uuid:salon_uid>/analytics/service-revenue", TopServicesRevenueView, name="service-revenue"),
    path("/<uuid:salon_uid>/analytics/product-categories", TopProductCategoryRevenueView, name="top-product-category"),
    path("/<uuid:salon_uid>/analytics/service-categories", TopServiceCategoryRevenueView, name="top-service-category"),
    path(
        "/<uuid:salon_uid>/bookings/<uuid:booking_uid>/receipt",
        SalonBookingReceiptDownloadAPIView.as_view(),
        name="salon.booking-receipt-download",
    ),
    path(
        "/<uuid:salon_uid>/lookbook/<uuid:lookbook_uid>",
        SalonLookBookDetailView.as_view(),
        name="salon.lookbook-detail",
    ),
    path(
        "/<uuid:salon_uid>/lookbook",
        SalonLookBookListView.as_view(),
        name="salon.lookbook-list",
    ),
    path(
        "/<uuid:salon_uid>/bookings/<uuid:booking_uid>",
        SalonBookingDetailView.as_view(),
        name="salon.booking-detail",
    ),
    path(
        "/<uuid:salon_uid>/bookings",
        SalonbookingListView.as_view(),
        name="salon.booking-list",
    ),
    path(
        "/<uuid:salon_uid>/chairs/<uuid:chair_uid>/bookings/<uuid:booking_uid>",
        SalonChairBookingDetailView.as_view(),
        name="salon.chair-booking-detail",
    ),
    path(
        "/<uuid:salon_uid>/chairs/<uuid:chair_uid>/bookings",
        SalonChairBookingListView.as_view(),
        name="salon.chair-booking-list",
    ),
    path(
        "/<uuid:salon_uid>/chairs/<uuid:chair_uid>",
        SalonChairDetailView.as_view(),
        name="salon.chair-detail",
    ),
    path(
        "/<uuid:salon_uid>/chairs",
        SalonChairListView.as_view(),
        name="salon.chair-list",
    ),
    path(
        "/<uuid:salon_uid>/booking-calendar/<uuid:booking_uid>",
        SalonBookingCalendarDetailView.as_view(),
        name="salon.booking-detail",
    ),
    path(
        "/<uuid:salon_uid>/booking-calendar",
        SalonBookingCalendarListView.as_view(),
        name="salon.booking-calendar",
    ),
    path(
        "/<uuid:salon_uid>/employees/<uuid:employee_uid>",
        SalonEmployeeDetailView.as_view(),
        name="salon.employee-detail",
    ),
    path(
        "/<uuid:salon_uid>/employees",
        SalonEmployeeListView.as_view(),
        name="salon.employee-list",
    ),
    path(
        "/<uuid:salon_uid>/products/<uuid:product_uid>",
        SalonProductDetailView.as_view(),
        name="salon.product-detail",
    ),
    path(
        "/<uuid:salon_uid>/products",
        SalonProductListView.as_view(),
        name="salon.product-list",
    ),
    path(
        "/<uuid:salon_uid>/services/<uuid:service_uid>",
        SalonServiceDetailView.as_view(),
        name="salon.service-detail",
    ),
    path(
        "/<uuid:salon_uid>/services",
        SalonServiceListView.as_view(),
        name="salon.service-list",
    ),
    path(
        "/<uuid:salon_uid>/dashboard",
        SalonDashboardApiView.as_view(),
        name="salon.dashboard",
    ),
    path(
        "/<uuid:salon_uid>",
        SalonDetailView.as_view(),
        name="salon.detail",
    ),
    path("", SalonListView.as_view(), name="salon.list"),
]
